### PR TITLE
Fix false positives for Actor System usage

### LINKED ISSUE #139: Laguna: unclear `_$3 is used as Akka message but does not extend...` (false positive?)
As reported by @LukBed (errors obfuscated):

```
[error] .....: _$3 is used as Akka message but does not extend a trait annotated with org.virtuslab.ash.annotation.SerializabilityTrait.
[error] Passing an object of class NOT extending SerializabilityTrait as a message may cause Akka to fall back to Java serialization during runtime.
[error] 
[error]     if (enableReflection) handle(WebHandler.grpcWebHandler(serviceImplementations :+ reflectionService: _*))
[error]                                                           ^
[error] ...: Make sure this type is itself annotated, or extends a type annotated with  @org.virtuslab.ash.annotation.SerializabilityTrait.
[error]   def grpcWebRouting(enableReflection: Boolean)(implicit system: ActorSystem[_]): Route =
[error]                                                                              ^
[error] ....: _$3 is used as Akka message but does not extend a trait annotated with org.virtuslab.ash.annotation.SerializabilityTrait.
[error] Passing an object of class NOT extending SerializabilityTrait as a message may cause Akka to fall back to Java serialization during runtime.
[error] 
[error]     else handle(WebHandler.grpcWebHandler(serviceImplementations: _*))
[error]                                          ^
[error] three errors found
```

### PR DESCRIPTION
**Pull request by LukaszKontowski**
Closes #139 
- more description in added comment for the new `typeArgsAreHiddenIgnoreTypes` method

### CODE REVIEW

File: serializability-checker-compiler-plugin/src/test/resources/GenericsTest3.scala [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+import akka.grpc.scaladsl.WebHandler
+import akka.http.scaladsl.model.{HttpRequest, HttpResponse}
+
+import scala.concurrent.Future
+
+object GenericsTest3 {
+
+  def invokeGrpcWebHandler(handlers: List[PartialFunction[HttpRequest, Future[HttpResponse]]])
+                                  (implicit as: ActorSystem[_]): HttpRequest => Future[HttpResponse] = {
+    // For some reason type parameter on below method call for implicitly passed ActorSystem[_] is not `scala.Any`
```
Comment (PawelLipski) [inline serializability-checker-compiler-plugin/src/test/resources/GenericsTest3.scala:13]: Wow... did you manage to reproduce it on any other type? no need to do an extra research ofc, just curious

Comment (PawelLipski) [reply serializability-checker-compiler-plugin/src/test/resources/GenericsTest3.scala:13]: (other than `WebHandler`)

File: serializability-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializabilityCheckerCompilerPluginComponent.scala [hunk 2]
```diff
@@ -196,5 +197,23 @@ class SerializabilityCheckerCompilerPluginComponent(
...
+
+      /*
+      It might happen that scala compiler translates the "[_]" wildcard from typeArgs
+      not to the "scala.Any" type, but to a temporary compiler-specific type.
+      String representation for such type ends with "._$<DIGIT>" (e.g. "._$2")
+      To catch such situations and not raise false error - we have to check it.
+      We should ignore scala.Any and other possible ignoredTypes in such cases.
+      In particular, mentioned problem might occur when using ActorSystem[_] implicitly as parameter.
+      For example, such scenario occurs when using object of type ActorSystem[_] in method calls
+      that in fact require akka.actor.ClassicActorSystemProvider (which is a supertype for ActorSystem).
```
Comment (PawelLipski) [inline serializability-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializabilityCheckerCompilerPluginComponent.scala:209]: +1, such comments will save a lot of time&effort further down the project lifecycle

File: serializability-checker-compiler-plugin/src/test/resources/GenericsTest3.scala (hunk 1 above)
Comment (LukaszKontowski) [reply serializability-checker-compiler-plugin/src/test/resources/GenericsTest3.scala:13]: No, I tried many times without using GRPC on some custom code with self-made ActorSystem[Any] but failed to reproduce the `._$1` dollar-digit style compiler type naming :/

File: serializability-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializabilityCheckerCompilerPluginComponent.scala [hunk 3]
```diff
@@ -196,5 +197,23 @@ class SerializabilityCheckerCompilerPluginComponent(
...
+       */
+      private def typeArgsAreHiddenIgnoreTypes(typ: global.Type): Boolean =
+        if (typ.typeSymbol.fullName.matches(".+\\._\\$\\d"))
```
Comment (PawelLipski) [inline serializability-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializabilityCheckerCompilerPluginComponent.scala:212]: Check `raw"..."` interpolator

File: serializability-checker-compiler-plugin/src/test/resources/GenericsTest3.scala (hunk 1 above)
Comment (LukaszKontowski) [reply serializability-checker-compiler-plugin/src/test/resources/GenericsTest3.scala:13]: That's why I decided to use GRPC - didn't find any other way to reproduce this case

File: project/Dependencies.scala [hunk 4]
```diff
@@ -24,6 +24,9 @@ object Dependencies {
   val akkaTestKitTyped = "com.typesafe.akka" %% "akka-actor-testkit-typed" % akkaVersion
   val akkaStreamTestKit = "com.typesafe.akka" %% "akka-stream-testkit" % akkaVersion
 
+  val akkaGrpcWebSupport = "ch.megard" %% "akka-http-cors" % "1.1.3"
```
Comment (PawelLipski) [inline project/Dependencies.scala:27]: Wow `akka-http-cors` provides **web support** for akka-grpc? 😯 I mean, I've used this lib... but for CORS in akka-http 😅  mostly asking out of curiosity, that's test code anyway

File: serializability-checker-compiler-plugin/src/test/resources/GenericsTest3.scala [hunk 5]
```diff
@@ -0,0 +1,18 @@
+package org.random.project
+
+import akka.actor.typed.ActorSystem
+import akka.grpc.scaladsl.WebHandler
+import akka.http.scaladsl.model.{HttpRequest, HttpResponse}
```
Comment (PawelLipski) [inline serializability-checker-compiler-plugin/src/test/resources/GenericsTest3.scala:5]: Maybe you just need akka-http and not akka-http-cors on the test classpath?

File: serializability-checker-compiler-plugin/src/test/resources/GenericsTest3.scala (hunk 1 above)
Comment (PawelLipski) [reply serializability-checker-compiler-plugin/src/test/resources/GenericsTest3.scala:13]: Wooow so the Łukasz's issue is even more exotic than I expected ;p

Comment (PawelLipski) [reply serializability-checker-compiler-plugin/src/test/resources/GenericsTest3.scala:13]: Might even be a bug/glitch/inconsistency in Scala (compiler) itself

File: serializability-checker-compiler-plugin/src/test/resources/GenericsTest3.scala (hunk 5 above)
Comment (LukaszKontowski) [reply serializability-checker-compiler-plugin/src/test/resources/GenericsTest3.scala:5]: `grpcWebHandler` is defined like this:
```
def grpcWebHandler(handlers: PartialFunction[HttpRequest, Future[HttpResponse]]*)(
      implicit as: ClassicActorSystemProvider,
      corsSettings: CorsSettings = defaultCorsSettings): HttpRequest => Future[HttpResponse] = {
    implicit val system = as.classicSystem
    val servicesHandler = ServiceHandler.concat(handlers: _*)
    Route.toFunction(cors(corsSettings) {
      handleWith(servicesHandler)
    })
  }
  ```
  
  with 
  `import ch.megard.akka.http.cors.scaladsl.settings.CorsSettings`
  
  I need to add akka-http-cors to the classpath, otherwise an error occurs:
  ```
  error: Symbol 'type ch.megard.akka.http.cors.scaladsl.settings.CorsSettings' is missing from the classpath.
  ```

Comment (PawelLipski) [reply serializability-checker-compiler-plugin/src/test/resources/GenericsTest3.scala:5]: Awww okay I see

File: project/Dependencies.scala (hunk 4 above)
Comment (LukaszKontowski) [reply project/Dependencies.scala:27]: `akka-http-cors` is used by the `akka.grpc.scaladsl.WebHandler` in it's methods and I just needed to add this ti the classpath for tests... I do not know the details...

File: serializability-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializabilityCheckerCompilerPluginComponent.scala (hunk 3 above)
Comment (LukaszKontowski) [reply serializability-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializabilityCheckerCompilerPluginComponent.scala:212]: I checked it, but I don't know how can it help with regular expression? Is there something wrong with current regex string `".+\\._\\$\\d"` ?

Comment (PawelLipski) [reply serializability-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializabilityCheckerCompilerPluginComponent.scala:212]: Oh! CMIIW... can backslashes remain un-escaped within `raw"..."` string? or maybe I confused it with `r"..."` from Python ;p

**Review by PawelLipski — APPROVED** [review]
