### PR TITLE
fixed  logic of `collectMissingClassNames`

### LINKED ISSUE #179: Fix `collectMissingClassNames` logic - codec-registration-checker-plugin
It shows up that current logic from `collectMissingClassNames` method does not work well in particular:
```
sourceCodeFilesAsStrings.exists(fileAsString => {
  fileAsString.startsWith(s"package $packageName") &&
  (fileAsString.contains(s"class $typeName") || fileAsString.contains(s"trait $typeName") || fileAsString
     .contains(s"object $typeName"))
})
```

It does not work well for scenarios where serializable trait is nested in an object, example:
https://github.com/VirtusLab/akka-on-kubernetes/blob/exercise-5-solution/server/src/main/scala/com/virtuslab/akkaonk8s/tictactoe/GameActor.scala

### PR DESCRIPTION
**Pull request by LukaszKontowski**
closes #179 
Removed invalid assumption about package names. Assumption was wrong as serializable traits can be nested.

### CODE REVIEW

File: codec-registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala [hunk 1]
```diff
@@ -204,12 +204,11 @@ class SerializerCheckCompilerPluginComponent(
 
         def typeIsDefinedInScalaFiles(fqcn: String): Boolean = {
           val indexOfLastDotInFQCN = fqcn.lastIndexOf('.')
-          val packageName = fqcn.substring(0, indexOfLastDotInFQCN)
           val typeName = fqcn.substring(indexOfLastDotInFQCN + 1)
           sourceCodeFilesAsStrings.exists(fileAsString => {
-            fileAsString.startsWith(s"package $packageName") &&
-            (fileAsString.contains(s"class $typeName") || fileAsString.contains(s"trait $typeName") || fileAsString
-              .contains(s"object $typeName"))
+            fileAsString.contains(s"class $typeName") ||
```
Comment (PawelLipski) [inline codec-registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala:209]: Huh so the condition is now relaxed... it's getting out of hand TBH 😅

Pls add a test and merge as is... but generally #171 will be very welcome if doable 🤔

Comment (LukaszKontowski) [reply codec-registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala:209]: Ok, I will do #171 soon then. Regarding regression testing - please take a look at two existing tests that we have. The first one ensures that plugin detects missing registrations. The second one ensures that we do not treat "false positives" as errors. Do we need another test case? If yes - what should be tested?

https://github.com/VirtusLab/akka-serialization-helper/blob/main/codec-registration-checker-compiler-plugin/src/test/scala/org/virtuslab/ash/CodecRegistrationCheckerCompilerPluginSpec.scala#L55-L63

and

https://github.com/VirtusLab/akka-serialization-helper/blob/main/codec-registration-checker-compiler-plugin/src/test/scala/org/virtuslab/ash/CodecRegistrationCheckerCompilerPluginSpec.scala#L55-L63

Comment (PawelLipski) [reply codec-registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala:209]: I'd specifically like a test that would've capture this bug! I.e. a one that would fail before this fix but won't fail anymore after the fix

Comment (PawelLipski) [reply codec-registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala:209]: That'll be useful esp. given that the logic is likely to be rewritten as part of #171

Comment (LukaszKontowski) [reply codec-registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala:209]: Test case added - "type that is missing in serializer definition is wrapped in an object" + small refactor in the test class to improve readability

**Review by PawelLipski — APPROVED** [review]
