### PR TITLE
Regex filter annotation for filtering types

### LINKED ISSUE #86: False negative in registration-checker-compiler-plugin
In Hydra (PR \#1167, commit 6b4f0b32a8897e7cd824c57cd986d41d9ab5b80e), I'm getting a 

```
....CirceAkkaSerializer - No codec found for [....] class. Call Register[A] for this class or its supertype and append result to codecs.
java.util.NoSuchElementException: key not found: ...
````

only in runtime (from `org.virtuslab.ash.circe.CirceAkkaSerializer#scanForSerializables`) even though this should've been reported in the compile time. Details on slack coz this refers to proprietary code

### PR DESCRIPTION
**Pull request by MarconZet**
close #86

### CODE REVIEW

File: registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala [hunk 1]
```diff
@@ -27,6 +28,7 @@ class SerializerCheckCompilerPluginComponent(
     s"Checks marked serializer for references to classes found in $serializerCheckPhaseName"
 
   private val serializerType = typeOf[Serializer]
+  private val serializerRegexFilter = typeOf[SerializerRegexFilter]
```
Comment (PawelLipski) [inline registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala:31]: Hmmm what is the regex specifically matched against? Also, is it "includes" or "fully matches" semantics?

File: registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala [hunk 2]
```diff
@@ -27,6 +28,7 @@ class SerializerCheckCompilerPluginComponent(
...
   private val serializabilityTraitType = typeOf[SerializabilityTrait]
```
Comment (PawelLipski) [inline registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala:32]: While you're here... I'd refine the error message a bit:

`not referenced in marked serializer` => `not registered` (?) `in a class annotated with @org.Serializer. This will lead to a missing codec for Akka serialization in the runtime`

Plus also maybe mention the regex? Since the class might be referenced but not within the desired regex

File: registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala [hunk 3]
```diff
@@ -27,6 +28,7 @@ class SerializerCheckCompilerPluginComponent(
...
 
   private var typesNotDumped = true
```
Comment (PawelLipski) [inline registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala:34]: Also, I'm getting a false positive on the current state of Hydra PR \#1190 (commit `c730950a2`) -- getting `<some-class> not referenced in marked serializer` despite it's located in line 72... oh, maybe the regex should have some extra `.*`s...

Comment (PawelLipski) [reply registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala:34]: Yeah, works with `.*Register.*`... but not with `Register.*`... does it match the entire source code lines?...

File: registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala (hunk 1 above)
Comment (MarconZet) [reply registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala:31]: Full match

File: registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala (hunk 3 above)
Comment (MarconZet) [reply registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala:34]: It doesn't match source code lines, but `String` representation of `Type`. So `Register` is actually a `org.virtuslab.ash.circe.Register[A]`

Comment (PawelLipski) [reply registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala:34]: Oh okay... if you could replace `.*Option.*` in the sample test with `scala\.Option\[.*\]` maybe, this will give more clarity (other than the docs ;) )

Comment (PawelLipski) [reply registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala:34]: Also! maybe instead of having a separate optional annotation... let's make the regex a param of `@Serializer` annotation? Since without specifying the regex, the user is very likely to get a false negative just as we did on Hydra

Comment (PawelLipski) [reply registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala:34]: Huh am I missing something? I've tried

```scala
@SerializerRegexFilter("org\\.virtuslab\\.ash\\.circe\\.Register\\[.*\\]")
```

but it fails... although `"org\\.virtuslab\\.ash\\.circe\\.Register.*" passes. 

`Register` is an object so I'd expect the type to be sth like `org.virtuslab.ash.circe.Register$` (??)

File: registration-checker-compiler-plugin/src/test/resources/serializers/CorrectSerializer.scala [hunk 4]
```diff
@@ -1,8 +1,9 @@
 package org.random.project
 
-import org.virtuslab.ash.Serializer
+import org.virtuslab.ash.annotation.{Serializer, SerializerRegexFilter}
 
 @Serializer(classOf[SerializableTrait])
+@SerializerRegexFilter(".*Option.*")
 class CorrectSerializer {
```
Comment (PawelLipski) [inline registration-checker-compiler-plugin/src/test/resources/serializers/CorrectSerializer.scala:7]: Also! a point valid for Hydra: will the plugin work as expected when the `Register`s are spread across multiple classes? As suggested on a recent Hydra PR (one class with codecs per package aka _module_)

Comment (MarconZet) [reply registration-checker-compiler-plugin/src/test/resources/serializers/CorrectSerializer.scala:7]: Suppose there are three traits and marker trait:
```scala
@SerializablilityTrait
trait Mark

sealed trait One extends Mark
sealed trait Two extends Mark
sealed trait Three extends Mark
```

This will compile correctly:

```scala
trait Codecs{
  implicit val codec = ???
}

@Serializer
class Serializer extends Codecs {
  lazy val codecs = Seq(Register[One], Register[Two], Register[Three])
}
```

While this will fail:

```scala
trait Registers{
 lazy val register = Seq(Register[One], Register[Two], Register[Three])
}

@Serializer
class Serializer extends Codecs {
  lazy val codecs = this.register
}
```

Comment (MarconZet) [reply registration-checker-compiler-plugin/src/test/resources/serializers/CorrectSerializer.scala:7]: If there are some in between traits, for example:

```scala
@SerializablilityTrait
trait Mark
trait Trans

sealed trait One extends Trans
sealed trait Two extends Trans
sealed trait Three extends Mark
```

Then this compiles:
```scala
@Serializer
class Serializer{
  lazy val codecs = Seq(Register[Trans], Register[Three])
}
```

This fails:
```scala
@Serializer
class Serializer{
  lazy val codecs = Seq(Register[One], Register[Two], Register[Three])
}
```

File: registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala (hunk 3 above)
Comment (MarconZet) [reply registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala:34]: I used TypeTag for detection, it's more consistent.

Comment (MarconZet) [reply registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala:34]: > `Register` is an object so I'd expect the type to be sth like `org.virtuslab.ash.circe.Register$` (??)

We detect types, not function calls. What gets detected is `org.virtuslab.ash.circe.Register.Registration[hydra.something.SomethingCommand]`

File: serializability-checker-library/src/main/scala/org/virtuslab/ash/annotation/Serializer.scala [hunk 5]
```diff
@@ -0,0 +1,6 @@
+package org.virtuslab.ash.annotation
+
+import scala.annotation.nowarn
+
+@nowarn("cat=unused")
+class Serializer(clazz: Class[_], regexPattern: String = ".*") extends scala.annotation.StaticAnnotation
```
Comment (PawelLipski) [inline serializability-checker-library/src/main/scala/org/virtuslab/ash/annotation/Serializer.scala:6]: Maybe `typeRegexPattern` for a bit more self-evidency

File: registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala [hunk 6]
```diff
@@ -2,15 +2,20 @@ package org.virtuslab.ash
...
 import scala.tools.nsc.Global
 import scala.tools.nsc.Phase
 import scala.tools.nsc.plugins.PluginComponent
 
 import org.virtuslab.ash.RegistrationCheckerCompilerPlugin.classSweepPhaseName
 import org.virtuslab.ash.RegistrationCheckerCompilerPlugin.serializerCheckPhaseName
+import org.virtuslab.ash.annotation.SerializabilityTrait
+import org.virtuslab.ash.annotation.Serializer
 
 class SerializerCheckCompilerPluginComponent(
```
Comment (PawelLipski) [inline registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala:20]: Pls publish the entire updated change on Sonatype so that I can test it against Phoenix `develop` (unless you've done so already)

Comment (MarconZet) [reply registration-checker-compiler-plugin/src/main/scala/org/virtuslab/ash/SerializerCheckCompilerPluginComponent.scala:20]: If you want to test it on Hydra, use `sbt publishLocal`. The version will be the same, as if I had published it on Sonatype.

**Review by PawelLipski — APPROVED** [review]
Ok, tested the latest commit against Hydra's develop, works fine
